name: Emacs CI Testing

on:
  push:
    paths-ignore: ['**.md', '**.adoc']
  pull_request:
    paths-ignore: ['**.md', '**.adoc']

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        emacs_version: ['28.1', '28.2', '29.1', '29.2', '29.3', '29.4', 'snapshot']

    runs-on: ${{matrix.os}}
    continue-on-error: ${{matrix.emacs_version == 'snapshot' || (matrix.emacs_version == '29.4' && matrix.os == 'windows-latest')}}
    env:
      ELDEV_ARGS: -dtTQC

    steps:
    - name: Set up Emacs
      uses: jcs090218/setup-emacs@master
      with:
        version: ${{matrix.emacs_version}}

    - name: Install Eldev
      uses: emacs-eldev/setup-eldev@v1

    - name: Check out the source code
      uses: actions/checkout@v4

    - name: Ensure that copyright notices are up-to-date
      run: eldev $ELDEV_ARGS -p doctor up-to-date-copyright --all-tests

    - name: Lint the project
      run: eldev $ELDEV_ARGS lint

    - name: Compile the project
      run: eldev $ELDEV_ARGS compile --warnings-as-errors

    - name: Test the project
      # Add --expect 10 to ensure a minimum number of tests!
      run: eldev $ELDEV_ARGS test
